services:
  app:
    build: .
    ports:
      - "${PORT}:5002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ./seeds:/app/seeds:ro
    restart: always

  db:
    image: mysql:latest # Change to MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} # MySQL uses MYSQL_ROOT_PASSWORD for root user
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # MySQL data directory
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DATABASE_PASSWORD}",
        ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:
